ci: add version check to release
Signed-off-by: Dominik Kolonits <dkolonit@cisco.com>

diff --git a/.github/workflows/release-image.yaml b/.github/workflows/release-image.yaml
--- a/.github/workflows/release-image.yaml
+++ b/.github/workflows/release-image.yaml
@@ -15,8 +15,29 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
+  checkout-version-check:
+    name: checkout & version check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+        with:
+          fetch-depth: 0
+
+      - name: Version check
+        run: |
+          GIT_VERSION=${GITHUB_REF%-*}
+          PYTHON_VERSION=$(grep -m 1 version pyproject.toml | grep -e '\d.\d.\d' -o)
+          if [[ "$GIT_VERSION" == "$PYTHON_VERSION" ]]; then
+            printf "PYTHON_VERSION: %s and GIT_VERSION: %s are matched" "$PYTHON_VERSION" "$GIT_VERSION"
+            printf "Version check passed"
+          else
+            printf "Version check failed, version in pyproject.toml: %s and git tag version: %s are mismatched" "$PYTHON_VERSION" "$GIT_VERSION"
+            exit 1
+          fi
   build-push:
     name: Build docker image - wfsrv
+    needs: [checkout-version-check]
     uses: ./.github/workflows/reusable-docker-build-push.yaml
     permissions:
       contents: "read"
